[anthropic]
api_key = "<your-anthropic-api-key>"

[snowflake]
account = "<your-account-identifier>"
user = "<your-username>"
private_key = """-----BEGIN ENCRYPTED PRIVATE KEY-----
<paste-your-encrypted-private-key-here>
-----END ENCRYPTED PRIVATE KEY-----"""
private_key_passphrase = "<your-private-key-passphrase>"
warehouse = "<your-warehouse>"
role = "<your-role>"
database = "<your-database>"
schema = "<your-schema>"